CREATE DEFINER=`root`@`localhost` PROCEDURE `rpa_insurance`.`SP_RPA_LNF`(
    IN IN_BATCH_ID       VARCHAR(100),
    IN IN_INSURANCE_TYPE VARCHAR(50),
    IN IN_CONTRACT_TYPE  VARCHAR(20)
)
BEGIN
    DECLARE v_row_count  INT        DEFAULT 0;
    DECLARE v_company_code VARCHAR(10) DEFAULT 'LNF';
    DECLARE v_target_ym  VARCHAR(6) DEFAULT '';
    DECLARE v_cutoff_ym  VARCHAR(6) DEFAULT '';

    DECLARE EXIT HANDLER FOR SQLEXCEPTION
    BEGIN
        DROP TEMPORARY TABLE IF EXISTS T_TEMP_RPA_LIFE_PROCESSED;
    END;

    SET v_target_ym = DATE_FORMAT(NOW(), '%Y%m');
    SET v_cutoff_ym = DATE_FORMAT(DATE_SUB(NOW(), INTERVAL 38 MONTH), '%Y%m');

    DROP TEMPORARY TABLE IF EXISTS T_TEMP_RPA_LIFE_PROCESSED;
    CREATE TEMPORARY TABLE T_TEMP_RPA_LIFE_PROCESSED LIKE T_RPA_LIFE_PROCESSED;

    -- ======================================================================
    --  CONTRACT TYPE : NEW (신계약) - 29 Columns Mapping
    -- ======================================================================
    IF UPPER(IN_CONTRACT_TYPE) = 'NEW' THEN
        
        INSERT INTO T_TEMP_RPA_LIFE_PROCESSED (
            SYS_ID, SYS_CREATE_DATE, SYS_MODIFY_DATE, CREATED_DT, COMPANY_CODE, BATCH_ID, CONTRACT_TYPE, EXCEL_ROW_INDEX,
            COLUMN_01, COLUMN_02, COLUMN_03, COLUMN_04, COLUMN_05, COLUMN_06, COLUMN_07, COLUMN_08, COLUMN_09, COLUMN_10,
            COLUMN_11, COLUMN_12, COLUMN_13, COLUMN_14, COLUMN_15, COLUMN_16, COLUMN_17, COLUMN_18, COLUMN_19, COLUMN_20,
            COLUMN_21, COLUMN_22, COLUMN_23, COLUMN_24, COLUMN_25, COLUMN_26, COLUMN_27, COLUMN_28, COLUMN_29
        )
        SELECT
            REPLACE(UUID(), '-', ''), UTC_TIMESTAMP(), UTC_TIMESTAMP(), UTC_TIMESTAMP(), v_company_code, BATCH_ID, CONTRACT_TYPE, EXCEL_ROW_INDEX,
            COLUMN_01, COLUMN_02, COLUMN_03, COLUMN_04, COLUMN_05, -- NO, 대리점, 대리점명, 본부, 본부명
            COLUMN_06, COLUMN_07, COLUMN_08, COLUMN_09, COLUMN_10, -- 지점, 지점명, 계약번호, 계약일자, 계약상태
            COLUMN_11, COLUMN_12, COLUMN_13, COLUMN_14, COLUMN_15, -- KRW, USD, 주계약, 특약, 출금일자
            COLUMN_16, COLUMN_17, COLUMN_18, COLUMN_19, COLUMN_20, -- 설계사, 설계사명, 계약자, 피보험자, 상품코드
            COLUMN_21, COLUMN_22, COLUMN_23, COLUMN_24, COLUMN_25, -- 상품명, 가입금액, 월환산, 연환산, CMP
            COLUMN_26, COLUMN_27, COLUMN_28, COLUMN_29             -- 납입기간, 납입(년), 납입주기, 납입방법
        FROM T_RPA_LIFE_RAW
        WHERE COMPANY_CODE = v_company_code AND BATCH_ID = IN_BATCH_ID AND UPPER(CONTRACT_TYPE) = UPPER(IN_CONTRACT_TYPE);

        -- [Rule] 1. 맨 마지막열 값 추가 (납기구분: 년납 / 납입월: 해당월)
        UPDATE T_TEMP_RPA_LIFE_PROCESSED SET COLUMN_30 = '년납', COLUMN_31 = v_target_ym WHERE UPPER(CONTRACT_TYPE) = UPPER(IN_CONTRACT_TYPE);

    -- ======================================================================
    --  CONTRACT TYPE : EXT (보유계약) - 44 Columns Mapping
    -- ======================================================================
    ELSEIF UPPER(IN_CONTRACT_TYPE) = 'EXT' THEN
        
        INSERT INTO T_TEMP_RPA_LIFE_PROCESSED (
            SYS_ID, SYS_CREATE_DATE, SYS_MODIFY_DATE, CREATED_DT, COMPANY_CODE, BATCH_ID, CONTRACT_TYPE, EXCEL_ROW_INDEX,
            COLUMN_01, COLUMN_02, COLUMN_03, COLUMN_04, COLUMN_05, COLUMN_06, COLUMN_07, COLUMN_08, COLUMN_09, COLUMN_10,
            COLUMN_11, COLUMN_12, COLUMN_13, COLUMN_14, COLUMN_15, COLUMN_16, COLUMN_17, COLUMN_18, COLUMN_19, COLUMN_20,
            COLUMN_21, COLUMN_22, COLUMN_23, COLUMN_24, COLUMN_25, COLUMN_26, COLUMN_27, COLUMN_28, COLUMN_29, COLUMN_30,
            COLUMN_31, COLUMN_32, COLUMN_33, COLUMN_34, COLUMN_35, COLUMN_36, COLUMN_37, COLUMN_38, COLUMN_39, COLUMN_40,
            COLUMN_41, COLUMN_42, COLUMN_43, COLUMN_44
        )
        SELECT
            REPLACE(UUID(), '-', ''), UTC_TIMESTAMP(), UTC_TIMESTAMP(), UTC_TIMESTAMP(), v_company_code, BATCH_ID, CONTRACT_TYPE, EXCEL_ROW_INDEX,
            COLUMN_01, COLUMN_02, COLUMN_03, COLUMN_04, COLUMN_05, -- NO, 영본부, 영본명, 대리점, 대리점명
            COLUMN_06, COLUMN_07, COLUMN_08, COLUMN_09, COLUMN_10, -- 본부, 본부명, 지점, 지점명, 수금설계
            COLUMN_11, COLUMN_12, COLUMN_13, COLUMN_14, COLUMN_15, -- 수금명, 모집설계, 모집명, 계약번호, 계약일자
            COLUMN_16, COLUMN_17, COLUMN_18, COLUMN_19, COLUMN_20, -- 계약자, 주민(계), 주소, 피보험, 주민(피)
            COLUMN_21, COLUMN_22, COLUMN_23, COLUMN_24, COLUMN_25, -- 상품코드, 상품명, 통화, 가입금, KRW
            COLUMN_26, COLUMN_27, COLUMN_28, COLUMN_29, COLUMN_30, -- USD, 신CMP, 유CMP, 계약상태, 상세상태
            COLUMN_31, COLUMN_32, COLUMN_33, COLUMN_34, COLUMN_35, -- 만기일, 소멸일, 납입방법, 납입주기, 이체일
            COLUMN_36, COLUMN_37, COLUMN_38, COLUMN_39, COLUMN_40, -- 입금상태, 보험기간, 납입기간, 유지년월, 유지횟수
            COLUMN_41, COLUMN_42, COLUMN_43, COLUMN_44             -- 최종납일, 최종방법, 갱신여부, 갱신번호
        FROM T_RPA_LIFE_RAW
        WHERE COMPANY_CODE = v_company_code AND BATCH_ID = IN_BATCH_ID AND UPPER(CONTRACT_TYPE) = UPPER(IN_CONTRACT_TYPE);

        -- [Rule] 1. [계약상태] in ('실효','시효','유지','청약') -> [소멸일자]='0000-00-00'
        UPDATE T_TEMP_RPA_LIFE_PROCESSED SET COLUMN_32 = '0000-00-00'
        WHERE UPPER(CONTRACT_TYPE) = UPPER(IN_CONTRACT_TYPE) AND COLUMN_29 IN ('실효', '시효', '유지', '청약');

        -- [Rule] 2. Pause skip

        -- [Rule] 3. [계약상태]='실효' & [유지년월] 38개월 경과 -> [계약상태]='시효'
        UPDATE T_TEMP_RPA_LIFE_PROCESSED SET COLUMN_29 = '시효'
        WHERE UPPER(CONTRACT_TYPE) = UPPER(IN_CONTRACT_TYPE) AND COLUMN_29 = '실효'
          AND COLUMN_39 IS NOT NULL AND COLUMN_39 <> '' AND REPLACE(COLUMN_39, '-', '') <= v_cutoff_ym;
    END IF;

    -- ======================================================================
    --  FINAL INSERT (Processed Table)
    -- ======================================================================
    INSERT INTO T_RPA_LIFE_PROCESSED (
        SYS_ID, SYS_CREATE_DATE, SYS_MODIFY_DATE, CREATED_DT, COMPANY_CODE, BATCH_ID, CONTRACT_TYPE, EXCEL_ROW_INDEX,
        COLUMN_01, COLUMN_02, COLUMN_03, COLUMN_04, COLUMN_05, COLUMN_06, COLUMN_07, COLUMN_08, COLUMN_09, COLUMN_10,
        COLUMN_11, COLUMN_12, COLUMN_13, COLUMN_14, COLUMN_15, COLUMN_16, COLUMN_17, COLUMN_18, COLUMN_19, COLUMN_20,
        COLUMN_21, COLUMN_22, COLUMN_23, COLUMN_24, COLUMN_25, COLUMN_26, COLUMN_27, COLUMN_28, COLUMN_29, COLUMN_30,
        COLUMN_31, COLUMN_32, COLUMN_33, COLUMN_34, COLUMN_35, COLUMN_36, COLUMN_37, COLUMN_38, COLUMN_39, COLUMN_40,
        COLUMN_41, COLUMN_42, COLUMN_43, COLUMN_44
    )
    SELECT
        SYS_ID, UTC_TIMESTAMP(), UTC_TIMESTAMP(), UTC_TIMESTAMP(), COMPANY_CODE, BATCH_ID, CONTRACT_TYPE, EXCEL_ROW_INDEX,
        COLUMN_01, COLUMN_02, COLUMN_03, COLUMN_04, COLUMN_05, COLUMN_06, COLUMN_07, COLUMN_08, COLUMN_09, COLUMN_10,
        COLUMN_11, COLUMN_12, COLUMN_13, COLUMN_14, COLUMN_15, COLUMN_16, COLUMN_17, COLUMN_18, COLUMN_19, COLUMN_20,
        COLUMN_21, COLUMN_22, COLUMN_23, COLUMN_24, COLUMN_25, COLUMN_26, COLUMN_27, COLUMN_28, COLUMN_29, COLUMN_30,
        COLUMN_31, COLUMN_32, COLUMN_33, COLUMN_34, COLUMN_35, COLUMN_36, COLUMN_37, COLUMN_38, COLUMN_39, COLUMN_40,
        COLUMN_41, COLUMN_42, COLUMN_43, COLUMN_44
    FROM T_TEMP_RPA_LIFE_PROCESSED;

    SET v_row_count = ROW_COUNT();
    DROP TEMPORARY TABLE IF EXISTS T_TEMP_RPA_LIFE_PROCESSED;
END