CREATE DEFINER=`root`@`localhost` PROCEDURE `rpa_insurance`.`SP_RPA_HDG`(
    IN IN_BATCH_ID       VARCHAR(100),
    IN IN_INSURANCE_TYPE VARCHAR(50),
    IN IN_CONTRACT_TYPE  VARCHAR(20)
)
BEGIN
    -- [DECLARE variables]
    DECLARE v_row_count    INT          DEFAULT 0;
    DECLARE v_company_code VARCHAR(10)  DEFAULT 'HDG';
    DECLARE v_target_ym    VARCHAR(6)   DEFAULT '';

    -- [DECLARE handler]
    DECLARE EXIT HANDLER FOR SQLEXCEPTION
    BEGIN
        DROP TEMPORARY TABLE IF EXISTS T_TEMP_RPA_HDG_PROCESSED;
        DROP TEMPORARY TABLE IF EXISTS tmp_dup_case;
        DROP TEMPORARY TABLE IF EXISTS tmp_agg_data;
    END;

    -- [SET internal logic]
    SET v_target_ym = DATE_FORMAT(NOW(), '%Y%m');

    -- [Initialize Temporary Table]
    DROP TEMPORARY TABLE IF EXISTS T_TEMP_RPA_HDG_PROCESSED;
    IF UPPER(IN_INSURANCE_TYPE) = 'LTR' THEN
        CREATE TEMPORARY TABLE T_TEMP_RPA_HDG_PROCESSED LIKE T_RPA_LONG_TERM_PROCESSED;
    ELSEIF UPPER(IN_INSURANCE_TYPE) = 'CAR' THEN
        CREATE TEMPORARY TABLE T_TEMP_RPA_HDG_PROCESSED LIKE T_RPA_CAR_PROCESSED;
    ELSEIF UPPER(IN_INSURANCE_TYPE) = 'GEN' THEN
        CREATE TEMPORARY TABLE T_TEMP_RPA_HDG_PROCESSED LIKE T_RPA_GENERAL_PROCESSED;
    END IF;

    -- ======================================================================
    -- 1. DATA MAPPING (NEW Contract - Explicit 53 Columns Input)
    -- ======================================================================
    IF UPPER(IN_CONTRACT_TYPE) = 'NEW' THEN

        INSERT INTO T_TEMP_RPA_HDG_PROCESSED (
            SYS_ID, SYS_CREATE_DATE, SYS_MODIFY_DATE, CREATED_DT, COMPANY_CODE, BATCH_ID, CONTRACT_TYPE,
            COLUMN_01, COLUMN_02, COLUMN_03, COLUMN_04, COLUMN_05, -- 영수일, 입력일, 개시일, 본부, 사업부
            COLUMN_06, COLUMN_07, COLUMN_08, COLUMN_09, COLUMN_10, -- 지점, 팀, 취급자, 코드, 사용인명
            COLUMN_11, COLUMN_12, COLUMN_13, COLUMN_14, COLUMN_15, -- 사용인코드, 계약번호, 보종명, 보종코드, 계약자
            COLUMN_16, COLUMN_17, COLUMN_18, COLUMN_19, COLUMN_20, -- 피보험자, 차량번호, 지역구분, 보험료, 월납기준보험료
            COLUMN_21, COLUMN_22, COLUMN_23, COLUMN_24, COLUMN_25, -- 보장구성비(후), 보장구성비(전), 신규담보P, 수정보험료, CSM
            COLUMN_26, COLUMN_27, COLUMN_28, COLUMN_29, COLUMN_30, -- CSM배수, 신규담보수정P, 할인전P, 공동인수P, 책임P
            COLUMN_31, COLUMN_32, COLUMN_33, COLUMN_34, COLUMN_35, -- 배서구분, 계약구분, 수납방법, 회차, 납방
            COLUMN_36, COLUMN_37, COLUMN_38, COLUMN_39, COLUMN_40, -- 유입유형, 전가입사, 신차, 할인할증, 납입기간
            COLUMN_41, COLUMN_42, COLUMN_43, COLUMN_44, COLUMN_45, -- 만기, 가계성, 만기일자, 전자서명여부, 실적분할
            COLUMN_46, COLUMN_47, COLUMN_48, COLUMN_49, COLUMN_50, -- 집중관리, 해지회차, 본인계약, 무해지, 만기구분
            COLUMN_51, COLUMN_52, COLUMN_53                        -- 갱신담보P, 30세만기P, 출생후보험료
        )
        SELECT
            REPLACE(UUID(), '-', ''), UTC_TIMESTAMP(), UTC_TIMESTAMP(), UTC_TIMESTAMP(), v_company_code, BATCH_ID, CONTRACT_TYPE,
            COLUMN_01, COLUMN_02, COLUMN_03, COLUMN_04, COLUMN_05,
            COLUMN_06, COLUMN_07, COLUMN_08, COLUMN_09, COLUMN_10,
            COLUMN_11, COLUMN_12, COLUMN_13, COLUMN_14, COLUMN_15,
            COLUMN_16, COLUMN_17, COLUMN_18, COLUMN_19, COLUMN_20,
            COLUMN_21, COLUMN_22, COLUMN_23, COLUMN_24, COLUMN_25,
            COLUMN_26, COLUMN_27, COLUMN_28, COLUMN_29, COLUMN_30,
            COLUMN_31, COLUMN_32, COLUMN_33, COLUMN_34, COLUMN_35,
            COLUMN_36, COLUMN_37, COLUMN_38, COLUMN_39, COLUMN_40,
            COLUMN_41, COLUMN_42, COLUMN_43, COLUMN_44, COLUMN_45,
            COLUMN_46, COLUMN_47, COLUMN_48, COLUMN_49, COLUMN_50,
            COLUMN_51, COLUMN_52, COLUMN_53
        FROM T_RPA_HYUNDAI_RAW
        WHERE COMPANY_CODE = v_company_code AND BATCH_ID = IN_BATCH_ID;

        -- [Rule 1] 맨 마지막열 값 추가 (3개 공통)
        -- 항목명I:납기구분(54), 항목명II:납입월(55), 항목명III:납입일(56)
        UPDATE T_TEMP_RPA_HDG_PROCESSED 
        SET COLUMN_54 = '년납', 
            COLUMN_55 = v_target_ym, 
            COLUMN_56 = COLUMN_01;

        -- [Rule 1-4] General Only: 항목명IV:납입주기(57)='일시납'
        IF UPPER(IN_INSURANCE_TYPE) = 'GEN' THEN
            UPDATE T_TEMP_RPA_HDG_PROCESSED SET COLUMN_57 = '일시납';
        END IF;

        -- [Rule 2] [계약번호] 정렬 후 [배서구분] IN ('추징', '환급') 행 삭제
        DELETE FROM T_TEMP_RPA_HDG_PROCESSED WHERE COLUMN_31 IN ('추징', '환급');

        -- ------------------------------------------------------------------
        -- A.1. NEW LTR Logic
        -- ------------------------------------------------------------------
        IF UPPER(IN_INSURANCE_TYPE) = 'LTR' THEN
            -- [Rule 3] 중복 계약번호: '철회' + '정상' 처리
            DROP TEMPORARY TABLE IF EXISTS tmp_dup_case;
            CREATE TEMPORARY TABLE tmp_dup_case SELECT COLUMN_12 FROM T_TEMP_RPA_HDG_PROCESSED GROUP BY COLUMN_12 HAVING SUM(COLUMN_31='철회')>0 AND SUM(COLUMN_31='정상')>0;
            UPDATE T_TEMP_RPA_HDG_PROCESSED t INNER JOIN tmp_dup_case d ON t.COLUMN_12 = d.COLUMN_12 SET t.COLUMN_31 = '철회';
            DELETE FROM T_TEMP_RPA_HDG_PROCESSED WHERE COLUMN_12 IN (SELECT COLUMN_12 FROM tmp_dup_case) AND (COLUMN_19 LIKE '-%' OR CAST(REPLACE(COLUMN_19,',','') AS SIGNED) < 0);
            -- [Rule 4] [개시일]!=해당월 행 삭제
            DELETE FROM T_TEMP_RPA_HDG_PROCESSED WHERE LEFT(COLUMN_03, 6) <> v_target_ym;

        -- ------------------------------------------------------------------
        -- A.2. NEW CAR Logic
        -- ------------------------------------------------------------------
        ELSEIF UPPER(IN_INSURANCE_TYPE) = 'CAR' THEN
            -- [Rule 3] 중복 계약번호: '취소' + '정상' 처리
            DROP TEMPORARY TABLE IF EXISTS tmp_dup_case;
            CREATE TEMPORARY TABLE tmp_dup_case SELECT COLUMN_12 FROM T_TEMP_RPA_HDG_PROCESSED GROUP BY COLUMN_12 HAVING SUM(COLUMN_31='취소')>0 AND SUM(COLUMN_31='정상')>0;
            UPDATE T_TEMP_RPA_HDG_PROCESSED t INNER JOIN tmp_dup_case d ON t.COLUMN_12 = d.COLUMN_12 SET t.COLUMN_31 = '취소';
            DELETE FROM T_TEMP_RPA_HDG_PROCESSED WHERE COLUMN_12 IN (SELECT COLUMN_12 FROM tmp_dup_case) AND (COLUMN_19 LIKE '-%' OR CAST(REPLACE(COLUMN_19,',','') AS SIGNED) < 0);
            -- [Rule 4] [계약구분]="공동인수" 합산
            DROP TEMPORARY TABLE IF EXISTS tmp_agg_data;
            CREATE TEMPORARY TABLE tmp_agg_data
            SELECT COLUMN_12, SUM(CAST(REPLACE(IFNULL(COLUMN_29,'0'),',','') AS SIGNED)) AS s29, SUM(CAST(REPLACE(IFNULL(COLUMN_24,'0'),',','') AS SIGNED)) AS s24, MIN(SYS_ID) AS mid
            FROM T_TEMP_RPA_HDG_PROCESSED WHERE COLUMN_32 LIKE '%공동인수%' GROUP BY COLUMN_12 HAVING COUNT(*)>1;
            UPDATE T_TEMP_RPA_HDG_PROCESSED t INNER JOIN tmp_agg_data a ON t.SYS_ID = a.mid SET t.COLUMN_29 = CAST(a.s29 AS CHAR), t.COLUMN_24 = CAST(a.s24 AS CHAR), t.COLUMN_19 = CAST(a.s29 AS CHAR);
            DELETE t FROM T_TEMP_RPA_HDG_PROCESSED t INNER JOIN tmp_agg_data a ON t.COLUMN_12 = a.COLUMN_12 WHERE t.SYS_ID <> a.mid;

        -- ------------------------------------------------------------------
        -- A.3. NEW GENERAL Logic
        -- ------------------------------------------------------------------
        ELSEIF UPPER(IN_INSURANCE_TYPE) = 'GEN' THEN
            -- [Rule 3-1] '취소' + '정상' 처리
            DROP TEMPORARY TABLE IF EXISTS tmp_dup_case;
            CREATE TEMPORARY TABLE tmp_dup_case SELECT COLUMN_12 FROM T_TEMP_RPA_HDG_PROCESSED GROUP BY COLUMN_12 HAVING SUM(COLUMN_31='취소')>0 AND SUM(COLUMN_31='정상')>0;
            UPDATE T_TEMP_RPA_HDG_PROCESSED t INNER JOIN tmp_dup_case d ON t.COLUMN_12 = d.COLUMN_12 SET t.COLUMN_31 = '취소';
            DELETE FROM T_TEMP_RPA_HDG_PROCESSED WHERE COLUMN_12 IN (SELECT COLUMN_12 FROM tmp_dup_case) AND (COLUMN_19 LIKE '-%' OR CAST(REPLACE(COLUMN_19,',','') AS SIGNED) < 0);
            -- [Rule 3-2] 모두 '정상'인 경우 합산 처리 (19 + 24)
            DROP TEMPORARY TABLE IF EXISTS tmp_agg_data;
            CREATE TEMPORARY TABLE tmp_agg_data
            SELECT COLUMN_12, SUM(CAST(REPLACE(IFNULL(COLUMN_19,'0'),',','') AS SIGNED)) AS s19, SUM(CAST(REPLACE(IFNULL(COLUMN_24,'0'),',','') AS SIGNED)) AS s24, MIN(SYS_ID) AS mid
            FROM T_TEMP_RPA_HDG_PROCESSED WHERE COLUMN_12 IN (SELECT COLUMN_12 FROM T_TEMP_RPA_HDG_PROCESSED GROUP BY COLUMN_12 HAVING COUNT(*)>1 AND SUM(COLUMN_31<>'정상')=0) GROUP BY COLUMN_12;
            UPDATE T_TEMP_RPA_HDG_PROCESSED t INNER JOIN tmp_agg_data a ON t.SYS_ID = a.mid SET t.COLUMN_19 = CAST(a.s19 AS CHAR), t.COLUMN_24 = CAST(a.s24 AS CHAR);
            DELETE t FROM T_TEMP_RPA_HDG_PROCESSED t INNER JOIN tmp_agg_data a ON t.COLUMN_12 = a.COLUMN_12 WHERE t.SYS_ID <> a.mid;
        END IF;

    END IF;

    -- ======================================================================
    -- 2. FINAL EXPLICIT INSERT (Mapping up to 57 Columns)
    -- ======================================================================
    IF UPPER(IN_INSURANCE_TYPE) = 'LTR' THEN
        INSERT INTO T_RPA_LONG_TERM_PROCESSED (
            SYS_ID, SYS_CREATE_DATE, SYS_MODIFY_DATE, CREATED_DT, COMPANY_CODE, BATCH_ID, CONTRACT_TYPE,
            COLUMN_01, COLUMN_02, COLUMN_03, COLUMN_04, COLUMN_05, -- 영수일, 입력일, 개시일, 본부, 사업부
            COLUMN_06, COLUMN_07, COLUMN_08, COLUMN_09, COLUMN_10, -- 지점, 팀, 취급자, 코드, 사용인명
            COLUMN_11, COLUMN_12, COLUMN_13, COLUMN_14, COLUMN_15, -- 사용인코드, 계약번호, 보종명, 보종코드, 계약자
            COLUMN_16, COLUMN_17, COLUMN_18, COLUMN_19, COLUMN_20, -- 피보험자, 차량번호, 지역구분, 보험료, 월납기준보험료
            COLUMN_21, COLUMN_22, COLUMN_23, COLUMN_24, COLUMN_25, -- 보장구성비(후), 보장구성비(전), 신규담보P, 수정보험료, CSM
            COLUMN_26, COLUMN_27, COLUMN_28, COLUMN_29, COLUMN_30, -- CSM배수, 신규담보수정P, 할인전P, 공동인수P, 책임P
            COLUMN_31, COLUMN_32, COLUMN_33, COLUMN_34, COLUMN_35, -- 배서구분, 계약구분, 수납방법, 회차, 납방
            COLUMN_36, COLUMN_37, COLUMN_38, COLUMN_39, COLUMN_40, -- 유입유형, 전가입사, 신차, 할인할증, 납입기간
            COLUMN_41, COLUMN_42, COLUMN_43, COLUMN_44, COLUMN_45, -- 만기, 가계성, 만기일자, 전자서명여부, 실적분할
            COLUMN_46, COLUMN_47, COLUMN_48, COLUMN_49, COLUMN_50, -- 집중관리, 해지회차, 본인계약, 무해지, 만기구분
            COLUMN_51, COLUMN_52, COLUMN_53, COLUMN_54, COLUMN_55, -- 갱신담보P, 30세만기P, 출생후보험료, 납기구분, 납입월
            COLUMN_56                                              -- 납입일
        )
        SELECT 
            SYS_ID, UTC_TIMESTAMP(), UTC_TIMESTAMP(), UTC_TIMESTAMP(), COMPANY_CODE, BATCH_ID, CONTRACT_TYPE,
            COLUMN_01, COLUMN_02, COLUMN_03, COLUMN_04, COLUMN_05, COLUMN_06, COLUMN_07, COLUMN_08, COLUMN_09, COLUMN_10,
            COLUMN_11, COLUMN_12, COLUMN_13, COLUMN_14, COLUMN_15, COLUMN_16, COLUMN_17, COLUMN_18, COLUMN_19, COLUMN_20,
            COLUMN_21, COLUMN_22, COLUMN_23, COLUMN_24, COLUMN_25, COLUMN_26, COLUMN_27, COLUMN_28, COLUMN_29, COLUMN_30,
            COLUMN_31, COLUMN_32, COLUMN_33, COLUMN_34, COLUMN_35, COLUMN_36, COLUMN_37, COLUMN_38, COLUMN_39, COLUMN_40,
            COLUMN_41, COLUMN_42, COLUMN_43, COLUMN_44, COLUMN_45, COLUMN_46, COLUMN_47, COLUMN_48, COLUMN_49, COLUMN_50,
            COLUMN_51, COLUMN_52, COLUMN_53, COLUMN_54, COLUMN_55, COLUMN_56
        FROM T_TEMP_RPA_HDG_PROCESSED;
    
    ELSEIF UPPER(IN_INSURANCE_TYPE) = 'CAR' THEN
        INSERT INTO T_RPA_CAR_PROCESSED (
            SYS_ID, SYS_CREATE_DATE, SYS_MODIFY_DATE, CREATED_DT, COMPANY_CODE, BATCH_ID, CONTRACT_TYPE,
            COLUMN_01, COLUMN_02, COLUMN_03, COLUMN_04, COLUMN_05, COLUMN_06, COLUMN_07, COLUMN_08, COLUMN_09, COLUMN_10,
            COLUMN_11, COLUMN_12, COLUMN_13, COLUMN_14, COLUMN_15, COLUMN_16, COLUMN_17, COLUMN_18, COLUMN_19, COLUMN_20,
            COLUMN_21, COLUMN_22, COLUMN_23, COLUMN_24, COLUMN_25, COLUMN_26, COLUMN_27, COLUMN_28, COLUMN_29, COLUMN_30,
            COLUMN_31, COLUMN_32, COLUMN_33, COLUMN_34, COLUMN_35, COLUMN_36, COLUMN_37, COLUMN_38, COLUMN_39, COLUMN_40,
            COLUMN_41, COLUMN_42, COLUMN_43, COLUMN_44, COLUMN_45, COLUMN_46, COLUMN_47, COLUMN_48, COLUMN_49, COLUMN_50,
            COLUMN_51, COLUMN_52, COLUMN_53, COLUMN_54, COLUMN_55, COLUMN_56
        )
        SELECT 
            SYS_ID, UTC_TIMESTAMP(), UTC_TIMESTAMP(), UTC_TIMESTAMP(), COMPANY_CODE, BATCH_ID, CONTRACT_TYPE,
            COLUMN_01, COLUMN_02, COLUMN_03, COLUMN_04, COLUMN_05, COLUMN_06, COLUMN_07, COLUMN_08, COLUMN_09, COLUMN_10,
            COLUMN_11, COLUMN_12, COLUMN_13, COLUMN_14, COLUMN_15, COLUMN_16, COLUMN_17, COLUMN_18, COLUMN_19, COLUMN_20,
            COLUMN_21, COLUMN_22, COLUMN_23, COLUMN_24, COLUMN_25, COLUMN_26, COLUMN_27, COLUMN_28, COLUMN_29, COLUMN_30,
            COLUMN_31, COLUMN_32, COLUMN_33, COLUMN_34, COLUMN_35, COLUMN_36, COLUMN_37, COLUMN_38, COLUMN_39, COLUMN_40,
            COLUMN_41, COLUMN_42, COLUMN_43, COLUMN_44, COLUMN_45, COLUMN_46, COLUMN_47, COLUMN_48, COLUMN_49, COLUMN_50,
            COLUMN_51, COLUMN_52, COLUMN_53, COLUMN_54, COLUMN_55, COLUMN_56
        FROM T_TEMP_RPA_HDG_PROCESSED;

    ELSEIF UPPER(IN_INSURANCE_TYPE) = 'GEN' THEN
        INSERT INTO T_RPA_GENERAL_PROCESSED (
            SYS_ID, SYS_CREATE_DATE, SYS_MODIFY_DATE, CREATED_DT, COMPANY_CODE, BATCH_ID, CONTRACT_TYPE,
            COLUMN_01, COLUMN_02, COLUMN_03, COLUMN_04, COLUMN_05, COLUMN_06, COLUMN_07, COLUMN_08, COLUMN_09, COLUMN_10,
            COLUMN_11, COLUMN_12, COLUMN_13, COLUMN_14, COLUMN_15, COLUMN_16, COLUMN_17, COLUMN_18, COLUMN_19, COLUMN_20,
            COLUMN_21, COLUMN_22, COLUMN_23, COLUMN_24, COLUMN_25, COLUMN_26, COLUMN_27, COLUMN_28, COLUMN_29, COLUMN_30,
            COLUMN_31, COLUMN_32, COLUMN_33, COLUMN_34, COLUMN_35, COLUMN_36, COLUMN_37, COLUMN_38, COLUMN_39, COLUMN_40,
            COLUMN_41, COLUMN_42, COLUMN_43, COLUMN_44, COLUMN_45, COLUMN_46, COLUMN_47, COLUMN_48, COLUMN_49, COLUMN_50,
            COLUMN_51, COLUMN_52, COLUMN_53, COLUMN_54, COLUMN_55, COLUMN_56, COLUMN_57
        )
        SELECT 
            SYS_ID, UTC_TIMESTAMP(), UTC_TIMESTAMP(), UTC_TIMESTAMP(), COMPANY_CODE, BATCH_ID, CONTRACT_TYPE,
            COLUMN_01, COLUMN_02, COLUMN_03, COLUMN_04, COLUMN_05, COLUMN_06, COLUMN_07, COLUMN_08, COLUMN_09, COLUMN_10,
            COLUMN_11, COLUMN_12, COLUMN_13, COLUMN_14, COLUMN_15, COLUMN_16, COLUMN_17, COLUMN_18, COLUMN_19, COLUMN_20,
            COLUMN_21, COLUMN_22, COLUMN_23, COLUMN_24, COLUMN_25, COLUMN_26, COLUMN_27, COLUMN_28, COLUMN_29, COLUMN_30,
            COLUMN_31, COLUMN_32, COLUMN_33, COLUMN_34, COLUMN_35, COLUMN_36, COLUMN_37, COLUMN_38, COLUMN_39, COLUMN_40,
            COLUMN_41, COLUMN_42, COLUMN_43, COLUMN_44, COLUMN_45, COLUMN_46, COLUMN_47, COLUMN_48, COLUMN_49, COLUMN_50,
            COLUMN_51, COLUMN_52, COLUMN_53, COLUMN_54, COLUMN_55, COLUMN_56, COLUMN_57
        FROM T_TEMP_RPA_HDG_PROCESSED;
    END IF;

    -- [Cleanup]
    SET v_row_count = ROW_COUNT();
    DROP TEMPORARY TABLE IF EXISTS T_TEMP_RPA_HDG_PROCESSED;
    DROP TEMPORARY TABLE IF EXISTS tmp_dup_case;
    DROP TEMPORARY TABLE IF EXISTS tmp_agg_data;

END